//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten_Mangement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int b_id { get; set; }
        public string b_type { get; set; }
        public int b_plat_number { get; set; }
        public byte[] b_ownership_paper { get; set; }
        public int employee_id { get; set; }
        public int gender_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
