//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten_Mangement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int P_id { get; set; }
        public int e_id { get; set; }
        public string pass { get; set; }
        public string forget { get; set; }
    }
}
