//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten_Mangement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester_works
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semester_works()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int sw_id { get; set; }
        public int student_id { get; set; }
        public int level_id { get; set; }
        public int subject_id { get; set; }
        public double test1 { get; set; }
        public double test2 { get; set; }
        public double final { get; set; }
        public double total { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
