//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten_Mangement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Semester_works = new HashSet<Semester_works>();
            this.Guadians = new HashSet<Guadian>();
            this.Semester_works1 = new HashSet<Semester_works>();
            this.Subjects = new HashSet<Subject>();
        }
    
        public int student_id { get; set; }
        public string student_name { get; set; }
        public int gender_id { get; set; }
        public string student_birth { get; set; }
        public byte[] student_photo { get; set; }
        public byte[] student_birth_certificaion { get; set; }
        public byte[] student_examination { get; set; }
        public string level_id { get; set; }
        public string student_address { get; set; }
        public string student_state { get; set; }
        public decimal student_fees { get; set; }
        public int class_id { get; set; }
    
        public virtual Classes_schedule Classes_schedule { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Semester_works> Semester_works { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guadian> Guadians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Semester_works> Semester_works1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
